import { StyleSheet } from 'react-native'

export const colors = {
  bluePrimary: '#1b2f8e',
  nonBlue: '#f4f4fb',
  lightBlue: '#8f98c0',
  aquamarine: '#36DDE7',
  yellow: '#d8d021',
  green: '#1bb546',
  red: '#cc1515',
  input: '#f9f9f9',
}

export const GlobalStyles = StyleSheet.create({
  title: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  blueButton: {
    width: '100%',
    backgroundColor: colors.bluePrimary,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
  },
  lightBlueButton: {
    width: '100%',
    backgroundColor: colors.lightBlue,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  redButton:{
    width: '100%',
    backgroundColor: colors.red,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 10,
  },
  greenButton: {
    width: '100%',
    backgroundColor: colors.green,
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 20,
    marginTop: 10,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
  },
  smallPickerContainer: {
    borderRadius: 10,
    borderWidth: 1,
    width: '50%',
    borderColor: colors.nonBlue,
    overflow: 'hidden',
    marginBottom: 20,
  },
  smallPicker: {
    height: 45,
    width: '100%',
    backgroundColor: colors.nonBlue,
  },
  bigPickerContainer: {
    borderRadius: 10,
    borderWidth: 1,
    width: '100%',
    borderColor: colors.input,
    overflow: 'hidden',
    marginBottom: 20,
  },
  bigPicker: {
    height: 50,
    width: '100%',
    backgroundColor: colors.input,
  },
  whitePicker: {
    height: 50,
    width: '100%',
    backgroundColor: 'white',
  },
 input: {
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.input,
    borderRadius: 10,
    padding: 15,
    marginBottom: 5,
    fontSize: 16,
    width: '100%',
  },
  bigInput: {
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.input,
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    fontSize: 16,
  },
  smallInput: {
    backgroundColor: colors.input,
    borderWidth: 1,
    borderColor: colors.input,
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    fontSize: 16,
    width: '50%',
  },
})
